services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wgg\MailchimpBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    Wgg\MailchimpBundle\MailchimpConfiguration: ~

    Wgg\MailchimpBundle\ApiClient: ~

    Wgg\MailchimpBundle\ListOptionsProvider:
        public: true

    Wgg\MailchimpBundle\Command\:
        resource: '../../Command'
        tags:
            - console.command

    Wgg\MailchimpBundle\Twig\Extension\MailchimpExtension:
        tags:
            - twig.extension
